Firma.Intranet/Controllers/AdresController.cs
using Firma.Data.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Firma.Intranet.Controllers
{
    public class AdresController : Controller
    {
        private readonly FirmaDbContext _context;

        public AdresController(FirmaDbContext context)
        {
            _context = context;
        }

        // GET: Adres
        public async Task<IActionResult> Index()
        {
            var firmaDbContext = _context.Adresy.Include(a => a.Kontrahent);
            return View(await firmaDbContext.ToListAsync());
        }

        // GET: Adres/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Adresy == null)
            {
                return NotFound();
            }

            var adres = await _context.Adresy
                .Include(a => a.Kontrahent)
                .FirstOrDefaultAsync(m => m.IdAdresu == id);
            if (adres == null)
            {
                return NotFound();
            }

            return View(adres);
        }

        // GET: Adres/Create
        public IActionResult Create()
        {
            ViewData["IdKontrahenta"] = new SelectList(_context.Kontrahenci, "IdKontrahenta", "Nazwa");
            return View();
        }

        // POST: Adres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdAdresu,Ulica,Miejscowosc,NrDomu,NrLokalu,KodPoczowy,Poczta,Kraj,Siedziba,Glowny,CzyAktywny,IdKontrahenta")] Adres adres)
        {

            if (ModelState.IsValid)
            {
                _context.Add(adres);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdKontrahenta"] = new SelectList(_context.Kontrahenci, "IdKontrahenta", "Nazwa", adres.IdKontrahenta);
            return View(adres);
        }

        // GET: Adres/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Adresy == null)
            {
                return NotFound();
            }

            var adres = await _context.Adresy.FindAsync(id);
            if (adres == null)
            {
                return NotFound();
            }
            ViewData["IdKontrahenta"] = new SelectList(_context.Kontrahenci, "IdKontrahenta", "Nazwa", adres.IdKontrahenta);
            return View(adres);
        }

        // POST: Adres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdAdresu,Ulica,Miejscowosc,NrDomu,NrLokalu,KodPoczowy,Poczta,Kraj,Siedziba,Glowny,CzyAktywny,IdKontrahenta")] Adres adres)
        {
            if (id != adres.IdAdresu)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(adres);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AdresExists(adres.IdAdresu))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdKontrahenta"] = new SelectList(_context.Kontrahenci, "IdKontrahenta", "Nazwa", adres.IdKontrahenta);
            return View(adres);
        }

        // GET: Adres/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Adresy == null)
            {
                return NotFound();
            }

            var adres = await _context.Adresy
                .Include(a => a.Kontrahent)
                .FirstOrDefaultAsync(m => m.IdAdresu == id);
            if (adres == null)
            {
                return NotFound();
            }

            return View(adres);
        }

        // POST: Adres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Adresy == null)
            {
                return Problem("Entity set 'FirmaDbContext.Adresy'  is null.");
            }
            var adres = await _context.Adresy.FindAsync(id);
            if (adres != null)
            {
                _context.Adresy.Remove(adres);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AdresExists(int id)
        {
            return _context.Adresy.Any(e => e.IdAdresu == id);
        }
    }
}

Firma.Intranet/Controllers/CenaController.cs
using Firma.Data.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Firma.Intranet.Controllers
{
    public class CenaController : Controller
    {
        private readonly FirmaDbContext _context;

        public CenaController(FirmaDbContext context)
        {
            _context = context;
        }

        // GET: Cena
        public async Task<IActionResult> Index()
        {
            var firmaDbContext = _context.Ceny.Include(c => c.Produkt).Include(c => c.TypCeny);
            return View(await firmaDbContext.ToListAsync());
        }

        // GET: Cena/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Ceny == null)
            {
                return NotFound();
            }

            var cena = await _context.Ceny
                .Include(c => c.Produkt)
                .Include(c => c.TypCeny)
                .FirstOrDefaultAsync(m => m.IdCeny == id);
            if (cena == null)
            {
                return NotFound();
            }

            return View(cena);
        }

        // GET: Cena/Create
        public IActionResult Create()
        {
            ViewData["IdProduktu"] = new SelectList(_context.Produkty, "IdProduktu", "Nazwa");
            ViewData["IdTypuCeny"] = new SelectList(_context.TypyCen, "IdTypuCeny", "Typ");
            return View();
        }

        // POST: Cena/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCeny,IdProduktu,IdTypuCeny,Wartosc,Waluta,CzyAktywna")] Cena cena)
        {

            if (ModelState.IsValid)
            {
                _context.Add(cena);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdProduktu"] = new SelectList(_context.Produkty, "IdProduktu", "Nazwa", cena.IdProduktu);
            ViewData["IdTypuCeny"] = new SelectList(_context.TypyCen, "IdTypuCeny", "Typ", cena.IdTypuCeny);
            return View(cena);
        }

        // GET: Cena/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Ceny == null)
            {
                return NotFound();
            }

            var cena = await _context.Ceny.FindAsync(id);
            if (cena == null)
            {
                return NotFound();
            }
            ViewData["IdProduktu"] = new SelectList(_context.Produkty, "IdProduktu", "Nazwa", cena.IdProduktu);
            ViewData["IdTypuCeny"] = new SelectList(_context.TypyCen, "IdTypuCeny", "Typ", cena.IdTypuCeny);
            return View(cena);
        }

        // POST: Cena/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdCeny,IdProduktu,IdTypuCeny,Wartosc,Waluta,CzyAktywna")] Cena cena)
        {
            if (id != cena.IdCeny)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cena);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CenaExists(cena.IdCeny))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdProduktu"] = new SelectList(_context.Produkty, "IdProduktu", "Nazwa", cena.IdProduktu);
            ViewData["IdTypuCeny"] = new SelectList(_context.TypyCen, "IdTypuCeny", "Typ", cena.IdTypuCeny);
            return View(cena);
        }

        // GET: Cena/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Ceny == null)
            {
                return NotFound();
            }

            var cena = await _context.Ceny
                .Include(c => c.Produkt)
                .Include(c => c.TypCeny)
                .FirstOrDefaultAsync(m => m.IdCeny == id);
            if (cena == null)
            {
                return NotFound();
            }

            return View(cena);
        }

        // POST: Cena/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Ceny == null)
            {
                return Problem("Entity set 'FirmaDbContext.Ceny'  is null.");
            }
            var cena = await _context.Ceny.FindAsync(id);
            if (cena != null)
            {
                _context.Ceny.Remove(cena);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CenaExists(int id)
        {
          return _context.Ceny.Any(e => e.IdCeny == id);
        }
    }
}

Firma.Intranet/Controllers/MonterController.cs
using Firma.Data.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Firma.Intranet.Controllers
{
    public class MonterController : Controller
    {
        private readonly FirmaDbContext _context;

        public MonterController(FirmaDbContext context)
        {
            _context = context;
        }

        // GET: Monter
        public async Task<IActionResult> Index()
        {
              return View(await _context.Monterzy.ToListAsync());
        }

        // GET: Monter/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Monterzy == null)
            {
                return NotFound();
            }

            var monter = await _context.Monterzy
                .FirstOrDefaultAsync(m => m.IdMontera == id);
            if (monter == null)
            {
                return NotFound();
            }

            return View(monter);
        }

        // GET: Monter/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Monter/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdMontera,Nazwa,Uwagi,CzyAktywny")] Monter monter)
        {

            if (ModelState.IsValid)
            {
                _context.Add(monter);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(monter);
        }

        // GET: Monter/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Monterzy == null)
            {
                return NotFound();
            }

            var monter = await _context.Monterzy.FindAsync(id);
            if (monter == null)
            {
                return NotFound();
            }
            return View(monter);
        }

        // POST: Monter/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdMontera,Nazwa,Uwagi,CzyAktywny")] Monter monter)
        {
            if (id != monter.IdMontera)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(monter);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MonterExists(monter.IdMontera))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(monter);
        }

        // GET: Monter/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Monterzy == null)
            {
                return NotFound();
            }

            var monter = await _context.Monterzy
                .FirstOrDefaultAsync(m => m.IdMontera == id);
            if (monter == null)
            {
                return NotFound();
            }

            return View(monter);
        }

        // POST: Monter/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Monterzy == null)
            {
                return Problem("Entity set 'FirmaDbContext.Monterzy'  is null.");
            }
            var monter = await _context.Monterzy.FindAsync(id);
            if (monter != null)
            {
                _context.Monterzy.Remove(monter);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MonterExists(int id)
        {
          return _context.Monterzy.Any(e => e.IdMontera == id);
        }
    }
}

Firma.Intranet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Firma.Intranet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Firma.Intranet.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Firma.Intranet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kontrahent" asp-action="Index">Kontrahent</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Adres" asp-action="Index">Adres</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produkt" asp-action="Index">Produkt</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cena" asp-action="Index">Cena</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TypCeny" asp-action="Index">Typ ceny</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TypProduktu" asp-action="Index">Typ produktu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ZlecenieKompletacji" asp-action="Index">Zlecenie kompletacji</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SkladnikZK" asp-action="Index">Skladnik ZK</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProduktUbocznyZK" asp-action="Index">Produkt uboczny ZK</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Monter" asp-action="Index">Monter</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ZlecenieZakupu" asp-action="Index">Zlecenie Zakupu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PozycjaZZ" asp-action="Index">Pozycja ZZ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RodzajTransportu" asp-action="Index">Rodzaj transportu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TypTransakcji" asp-action="Index">Typ transakcji</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SposobDostawy" asp-action="Index">Sposób dostawy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SposobPlatnosci" asp-action="Index">Sposób płatności</a>
                        </li>
                    </ul>
                </div>
            </div>

        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Firma.Intranet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>