Firma.Intranet/Controllers/ProduktUbocznyZKController.cs
using Firma.Data.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Firma.Intranet.Controllers
{
    public class ProduktUbocznyZKController : Controller
    {
        private readonly FirmaDbContext _context;

        public ProduktUbocznyZKController(FirmaDbContext context)
        {
            _context = context;
        }

        // GET: ProduktUbocznyZK
        public async Task<IActionResult> Index()
        {
            var firmaDbContext = _context.PrUboczneZleceniaKompletacji
                .Include(p => p.Produkt)
                .Include(p => p.ZlecenieKompletacji);
            return View(await firmaDbContext.ToListAsync());
        }

        // GET: ProduktUbocznyZK/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.PrUboczneZleceniaKompletacji == null)
            {
                return NotFound();
            }

            var produktUbocznyZK = await _context.PrUboczneZleceniaKompletacji
                .Include(p => p.Produkt)
                .Include(p => p.ZlecenieKompletacji)
                .FirstOrDefaultAsync(m => m.IdPrUbocznego == id);
            if (produktUbocznyZK == null)
            {
                return NotFound();
            }

            return View(produktUbocznyZK);
        }

        // GET: ProduktUbocznyZK/Create
        public IActionResult Create()
        {
            ViewData["IdProduktu"] = new SelectList(_context.Produkty, "IdProduktu", "Nazwa");
            ViewData["IdZleceniaKompletacji"] = new SelectList(_context.ZleceniaKompletacji, "IdZleceniaKompletacji", "IdZleceniaKompletacji");
            return View();
        }

        // POST: ProduktUbocznyZK/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdPrUbocznego,IdZleceniaKompletacji,IdProduktu,Ilosc,CzyAktywny")] ProduktUbocznyZK produktUbocznyZK)
        {
            if (ModelState.IsValid)
            {
                _context.Add(produktUbocznyZK);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdProduktu"] = new SelectList(_context.Produkty, "IdProduktu", "Nazwa", produktUbocznyZK.IdProduktu);
            ViewData["IdZleceniaKompletacji"] = new SelectList(_context.ZleceniaKompletacji, "IdZleceniaKompletacji", "IdZleceniaKompletacji", produktUbocznyZK.IdZleceniaKompletacji);
            return View(produktUbocznyZK);
        }

        // GET: ProduktUbocznyZK/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.PrUboczneZleceniaKompletacji == null)
            {
                return NotFound();
            }

            var produktUbocznyZK = await _context.PrUboczneZleceniaKompletacji.FindAsync(id);
            if (produktUbocznyZK == null)
            {
                return NotFound();
            }
            ViewData["IdProduktu"] = new SelectList(_context.Produkty, "IdProduktu", "Nazwa", produktUbocznyZK.IdProduktu);
            ViewData["IdZleceniaKompletacji"] = new SelectList(_context.ZleceniaKompletacji, "IdZleceniaKompletacji", "IdZleceniaKompletacji", produktUbocznyZK.IdZleceniaKompletacji);
            return View(produktUbocznyZK);
        }

        // POST: ProduktUbocznyZK/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdPrUbocznego,IdZleceniaKompletacji,IdProduktu,Ilosc,CzyAktywny")] ProduktUbocznyZK produktUbocznyZK)
        {
            if (id != produktUbocznyZK.IdPrUbocznego)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(produktUbocznyZK);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProduktUbocznyZKExists(produktUbocznyZK.IdPrUbocznego))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdProduktu"] = new SelectList(_context.Produkty, "IdProduktu", "Nazwa", produktUbocznyZK.IdProduktu);
            ViewData["IdZleceniaKompletacji"] = new SelectList(_context.ZleceniaKompletacji, "IdZleceniaKompletacji", "IdZleceniaKompletacji", produktUbocznyZK.IdZleceniaKompletacji);
            return View(produktUbocznyZK);
        }

        // GET: ProduktUbocznyZK/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.PrUboczneZleceniaKompletacji == null)
            {
                return NotFound();
            }

            var produktUbocznyZK = await _context.PrUboczneZleceniaKompletacji
                .Include(p => p.Produkt)
                .Include(p => p.ZlecenieKompletacji)
                .FirstOrDefaultAsync(m => m.IdPrUbocznego == id);
            if (produktUbocznyZK == null)
            {
                return NotFound();
            }

            return View(produktUbocznyZK);
        }

        // POST: ProduktUbocznyZK/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.PrUboczneZleceniaKompletacji == null)
            {
                return Problem("Entity set 'FirmaDbContext.PrUboczneZleceniaKompletacji'  is null.");
            }
            var produktUbocznyZK = await _context.PrUboczneZleceniaKompletacji.FindAsync(id);
            if (produktUbocznyZK != null)
            {
                _context.PrUboczneZleceniaKompletacji.Remove(produktUbocznyZK);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProduktUbocznyZKExists(int id)
        {
            return _context.PrUboczneZleceniaKompletacji.Any(e => e.IdPrUbocznego == id);
        }
    }
}

Firma.Intranet/Controllers/SkladnikZKController.cs
using Firma.Data.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Firma.Intranet.Controllers
{
    public class SkladnikZKController : Controller
    {
        private readonly FirmaDbContext _context;

        public SkladnikZKController(FirmaDbContext context)
        {
            _context = context;
        }

        // GET: SkladnikZK
        public async Task<IActionResult> Index()
        {
            var firmaDbContext = _context.SkładnikiZleceniaKompletacji
                .Include(s => s.Produkt)
                .Include(s => s.ZlecenieKompletacji);
            return View(await firmaDbContext.ToListAsync());
        }

        // GET: SkladnikZK/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.SkładnikiZleceniaKompletacji == null)
            {
                return NotFound();
            }

            var skladnikZK = await _context.SkładnikiZleceniaKompletacji
                .Include(s => s.Produkt)
                .Include(s => s.ZlecenieKompletacji)
                .FirstOrDefaultAsync(m => m.IdSkladnika == id);
            if (skladnikZK == null)
            {
                return NotFound();
            }

            return View(skladnikZK);
        }

        // GET: SkladnikZK/Create
        public IActionResult Create()
        {
            ViewData["IdProduktu"] = new SelectList(_context.Produkty, "IdProduktu", "Nazwa");
            ViewData["IdZleceniaKompletacji"] = new SelectList(_context.ZleceniaKompletacji, "IdZleceniaKompletacji", "IdZleceniaKompletacji");
            return View();
        }

        // POST: SkladnikZK/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdSkladnika,IdZleceniaKompletacji,IdProduktu,Ilosc,CzyAktywny")] SkladnikZK skladnikZK)
        {
            if (ModelState.IsValid)
            {
                _context.Add(skladnikZK);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdProduktu"] = new SelectList(_context.Produkty, "IdProduktu", "Nazwa", skladnikZK.IdProduktu);
            ViewData["IdZleceniaKompletacji"] = new SelectList(_context.ZleceniaKompletacji, "IdZleceniaKompletacji", "IdZleceniaKompletacji", skladnikZK.IdZleceniaKompletacji);
            return View(skladnikZK);
        }

        // GET: SkladnikZK/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.SkładnikiZleceniaKompletacji == null)
            {
                return NotFound();
            }

            var skladnikZK = await _context.SkładnikiZleceniaKompletacji.FindAsync(id);
            if (skladnikZK == null)
            {
                return NotFound();
            }
            ViewData["IdProduktu"] = new SelectList(_context.Produkty, "IdProduktu", "Nazwa", skladnikZK.IdProduktu);
            ViewData["IdZleceniaKompletacji"] = new SelectList(_context.ZleceniaKompletacji, "IdZleceniaKompletacji", "IdZleceniaKompletacji", skladnikZK.IdZleceniaKompletacji);
            return View(skladnikZK);
        }

        // POST: SkladnikZK/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdSkladnika,IdZleceniaKompletacji,IdProduktu,Ilosc,CzyAktywny")] SkladnikZK skladnikZK)
        {
            if (id != skladnikZK.IdSkladnika)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(skladnikZK);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SkladnikZKExists(skladnikZK.IdSkladnika))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdProduktu"] = new SelectList(_context.Produkty, "IdProduktu", "Nazwa", skladnikZK.IdProduktu);
            ViewData["IdZleceniaKompletacji"] = new SelectList(_context.ZleceniaKompletacji, "IdZleceniaKompletacji", "IdZleceniaKompletacji", skladnikZK.IdZleceniaKompletacji);
            return View(skladnikZK);
        }

        // GET: SkladnikZK/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.SkładnikiZleceniaKompletacji == null)
            {
                return NotFound();
            }

            var skladnikZK = await _context.SkładnikiZleceniaKompletacji
                .Include(s => s.Produkt)
                .Include(s => s.ZlecenieKompletacji)
                .FirstOrDefaultAsync(m => m.IdSkladnika == id);
            if (skladnikZK == null)
            {
                return NotFound();
            }

            return View(skladnikZK);
        }

        // POST: SkladnikZK/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.SkładnikiZleceniaKompletacji == null)
            {
                return Problem("Entity set 'FirmaDbContext.SkładnikiZleceniaKompletacji'  is null.");
            }
            var skladnikZK = await _context.SkładnikiZleceniaKompletacji.FindAsync(id);
            if (skladnikZK != null)
            {
                _context.SkładnikiZleceniaKompletacji.Remove(skladnikZK);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SkladnikZKExists(int id)
        {
            return _context.SkładnikiZleceniaKompletacji.Any(e => e.IdSkladnika == id);
        }
    }
}

Firma.Intranet/Views/ZlecenieKompletacji/Create.cshtml
@model Firma.Data.Model.ZlecenieKompletacji
@using Firma.Intranet.ViewResources
@{
    ViewData["Title"] = @Resource.DodajNowyEl;
}
<h1>@Resource.DodajNowyEl</h1>
<h4>@Resource.ZlecenieKompletacji</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdKontrahenta" class="control-label"></label>
                <select asp-for="IdKontrahenta" class="form-control" asp-items="ViewBag.IdKontrahenta"></select>
            </div>
            <div class="form-group">
                <label asp-for="DataWystawienia" class="control-label"></label>
                <input asp-for="DataWystawienia" class="form-control" />
                <span asp-validation-for="DataWystawienia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OczekiwanaDataRealizacji" class="control-label"></label>
                <input asp-for="OczekiwanaDataRealizacji" class="form-control" />
                <span asp-validation-for="OczekiwanaDataRealizacji" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PotwierdzonaDataRealizacji" class="control-label"></label>
                <input asp-for="PotwierdzonaDataRealizacji" class="form-control" />
                <span asp-validation-for="PotwierdzonaDataRealizacji" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdProduktu" class="control-label"></label>
                <select asp-for="IdProduktu" class="form-control" asp-items="ViewBag.IdProduktu"></select>
            </div>
            <div class="form-group">
                <label asp-for="Ilosc" class="control-label"></label>
                <input asp-for="Ilosc" class="form-control" />
                <span asp-validation-for="Ilosc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdMontera" class="control-label"></label>
                <select asp-for="IdMontera" class="form-control" asp-items="ViewBag.IdMontera"></select>
            </div>
            <div class="form-group">
                <label asp-for="Priorytet" class="control-label"></label>
                <input asp-for="Priorytet" class="form-control" />
                <span asp-validation-for="Priorytet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CzasZlecenia" class="control-label"></label>
                <input asp-for="CzasZlecenia" class="form-control" />
                <span asp-validation-for="CzasZlecenia" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="CzyAktywne" checked="true" /> @Html.DisplayNameFor(model => model.CzyAktywne)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value=@Resource.Zapisz class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">@Resource.PowrotDoListy</a>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Firma.Intranet/Views/ZlecenieKompletacji/Delete.cshtml
@model Firma.Data.Model.ZlecenieKompletacji
@using Firma.Intranet.ViewResources
@{
    ViewData["Title"] = @Resource.Usuwanie;
}
<h1>@Resource.Usuwanie</h1>
<h3>@Resource.CzyNapewno1</h3>
<div>
    <h4>@Resource.ZlecenieKompletacji</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdZleceniaKompletacji)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdZleceniaKompletacji)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Kontrahent)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Kontrahent.Nazwa)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Produkt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Produkt.Nazwa)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Monter)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Monter.Nazwa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataWystawienia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataWystawienia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OczekiwanaDataRealizacji)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OczekiwanaDataRealizacji)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PotwierdzonaDataRealizacji)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PotwierdzonaDataRealizacji)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ilosc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ilosc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Priorytet)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Priorytet)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CzasZlecenia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CzasZlecenia)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CzyAktywne)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CzyAktywne)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdZleceniaKompletacji" />
        <input type="submit" value=@Resource.Usun class="btn btn-danger" /> |
        <a asp-action="Index">@Resource.PowrotDoListy</a>
    </form>
</div>

Firma.Intranet/Views/ZlecenieKompletacji/Details.cshtml
@model Firma.Data.Model.ZlecenieKompletacji
@using Firma.Intranet.ViewResources
@{
    ViewData["Title"] = @Resource.Szczegoly;
}
<h1>@Resource.Szczegoly</h1>
<div>
    <h4>@Resource.ZlecenieKompletacji</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdZleceniaKompletacji)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdZleceniaKompletacji)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Kontrahent)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Kontrahent.Nazwa)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Produkt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Produkt.Nazwa)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Monter)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Monter.Nazwa)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataWystawienia)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataWystawienia)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OczekiwanaDataRealizacji)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OczekiwanaDataRealizacji)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PotwierdzonaDataRealizacji)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PotwierdzonaDataRealizacji)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ilosc)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ilosc)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Priorytet)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Priorytet)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CzasZlecenia)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CzasZlecenia)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CzyAktywne)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CzyAktywne)
        </dd>
        <dd></dd>
        <dd></dd>
        <h5>@Resource.SkladnikiZlecenia</h5>
        <dd>
            <table class="table">
                <tr>
                    <th>Produkt</th>
                    <th>Ilość</th>
                </tr>
                @foreach (var item in Model.SkladnikZK)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Produkt.Nazwa)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ilosc)
                        </td>
                        <td>
                            <a asp-controller="SkladnikZK" asp-action="Edit" asp-route-id="@item.IdSkladnika">@Resource.Edycja</a> |
                            <a asp-controller="SkladnikZK" asp-action="Delete" asp-route-id="@item.IdSkladnika">@Resource.Usun</a>
                        </td>
                    </tr>
                }
            </table>
        </dd>
        <dd></dd>
        <dd></dd>
        <h5>@Resource.ProduktyUboczne</h5>
        <dd>
            <table class="table">
                <tr>
                    <th>Produkt</th>
                    <th>Ilość</th>
                </tr>
                @foreach (var item in Model.ProduktUbocznyZK)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Produkt.Nazwa)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ilosc)
                        </td>
                        <td>
                            <a asp-controller="ProduktUbocznyZK" asp-action="Edit" asp-route-id="@item.IdPrUbocznego">@Resource.Edycja</a> |
                            <a asp-controller="ProduktUbocznyZK" asp-action="Delete" asp-route-id="@item.IdPrUbocznego">@Resource.Usun</a>
                        </td>
                    </tr>
                }
            </table>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdZleceniaKompletacji">@Resource.Edycja</a> |
    <a asp-action="Index">@Resource.PowrotDoListy</a>
</div>

Firma.Intranet/Views/ZlecenieKompletacji/Edit.cshtml
@model Firma.Data.Model.ZlecenieKompletacji
@using Firma.Intranet.ViewResources
@{
    ViewData["Title"] = @Resource.Edycja;
}
<h1>@Resource.Edycja</h1>
<h4>@Resource.ZlecenieKompletacji</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdZleceniaKompletacji" />
            <div class="form-group">
                <label asp-for="IdKontrahenta" class="control-label"></label>
                <select asp-for="IdKontrahenta" class="form-control" asp-items="ViewBag.IdKontrahenta"></select>
                <span asp-validation-for="IdKontrahenta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataWystawienia" class="control-label"></label>
                <input asp-for="DataWystawienia" class="form-control" />
                <span asp-validation-for="DataWystawienia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OczekiwanaDataRealizacji" class="control-label"></label>
                <input asp-for="OczekiwanaDataRealizacji" class="form-control" />
                <span asp-validation-for="OczekiwanaDataRealizacji" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PotwierdzonaDataRealizacji" class="control-label"></label>
                <input asp-for="PotwierdzonaDataRealizacji" class="form-control" />
                <span asp-validation-for="PotwierdzonaDataRealizacji" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdProduktu" class="control-label"></label>
                <select asp-for="IdProduktu" class="form-control" asp-items="ViewBag.IdProduktu"></select>
                <span asp-validation-for="IdProduktu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ilosc" class="control-label"></label>
                <input asp-for="Ilosc" class="form-control" />
                <span asp-validation-for="Ilosc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdMontera" class="control-label"></label>
                <select asp-for="IdMontera" class="form-control" asp-items="ViewBag.IdMontera"></select>
                <span asp-validation-for="IdMontera" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Priorytet" class="control-label"></label>
                <input asp-for="Priorytet" class="form-control" />
                <span asp-validation-for="Priorytet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CzasZlecenia" class="control-label"></label>
                <input asp-for="CzasZlecenia" class="form-control" />
                <span asp-validation-for="CzasZlecenia" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="CzyAktywne" /> @Html.DisplayNameFor(model => model.CzyAktywne)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value=@Resource.Zapisz class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">@Resource.PowrotDoListy</a>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}