FirmaWebApp/Controllers/CartController.cs
using Firma.Data.Model;
using FirmaWebApp.Models.BusinessLogic;
using FirmaWebApp.Models.Shop;
using Microsoft.AspNetCore.Mvc;

namespace FirmaWebApp.Controllers
{
    public class CartController : Controller
    {
        private readonly FirmaDbContext _context;
        public CartController(FirmaDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            CartB cart = new CartB(this._context, this.HttpContext);
            var cartData = new CartData
            {
                CartItems = await cart.GetCartItems(),
                Total = await cart.GetTotal()
            };
            return View(cartData);
        }
        
        public async Task<ActionResult> AddToCart(int id)
        {
            CartB cart = new CartB(this._context, this.HttpContext);
            cart.AddToCart(await _context.Produkty.FindAsync(id));
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> RemoveFromCart(int id)
        {
            CartB cart = new CartB(this._context, this.HttpContext);
            cart.RemoveFromCart(id);
            return RedirectToAction("Index");
        }

    }
}

FirmaWebApp/Controllers/OrderDataController.cs
using Firma.Data.Model;
using FirmaWebApp.Models.BusinessLogic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace FirmaWebApp.Controllers
{
    public class OrderDataController : Controller
    {
        private readonly FirmaDbContext _context;
        
        public OrderDataController(FirmaDbContext context)
        {
            this._context = context;
        }

        public IActionResult KontrahentData()
        {
            return View();
        }

        public IActionResult AdresData()
        {
            return View();
        }

        public IActionResult ZZData()
        {
            ViewData["IdSposobuPlatnosci"] = new SelectList(_context.SposobyPlatnosci, "IdSposobuPlatnosci", "Nazwa");
            ViewData["IdSposobuDostawy"] = new SelectList(_context.SposobyDostawy, "IdSposobuDostawy", "Nazwa");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> KontrahentData([Bind("Akronim, Nazwa, Nip")] Kontrahent kontrahent)
        {
            //ModelState.Remove("Status");
            if (ModelState.IsValid)
            {
                kontrahent.CzyAktywny = true;
                kontrahent.IdSposobuPlatnosci = _context.SposobyPlatnosci.Select(sp=>sp.IdSposobuPlatnosci).FirstOrDefault();
                //if
                await _context.AddAsync(kontrahent);
                await _context.SaveChangesAsync();

                return RedirectToAction("AdresData", new { id = kontrahent.IdKontrahenta });
            }
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AdresData([Bind("Ulica, Miejscowosc, NrDomu, NrLokalu, KodPoczowy, Poczta, Kraj")] Adres adres, int id)
        {
            //ModelState.Remove("Status");
            if (ModelState.IsValid)
            {
                adres.Glowny = true;
                adres.Siedziba = true;
                adres.CzyAktywny = true;
                adres.IdKontrahenta = id;

                await _context.AddAsync(adres);
                await _context.SaveChangesAsync();

                return RedirectToAction("ZZData", new { id });
            }
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ZZData([Bind("IdSposobuDostawy, IdSposobuPlatnosci")] ZlecenieZakupu order, int id) 
        {
            CartB cartB = new CartB(this._context, this.HttpContext);
            var cartItems = await cartB.GetCartItems();

            ModelState.Remove("Status");
            if (ModelState.IsValid)
            {
                order.IdKontrahenta = id;
                order.IdTransakcji = 1;
                order.IdRodzajuTransportu = 1;
                order.DataWystawienia = DateTime.Now;
                order.Status = "w weryfikacji";
                order.NrOferty = "sklep internetowy";
                order.CzyAktywne = true;
                order.CzyPotwierdzone = false;
                order.TotalOrder = cartB.GetTotal().Result;

                await _context.AddAsync(order);
                await _context.SaveChangesAsync();

                foreach (var item in cartItems)
                {
                    var orderItem = new PozycjaZZ
                    {
                        IdProduktu = item.IdProduktu,
                        IdZleceniaZakupu = order.IdZleceniaZakupu,
                        Ilosc = item.Ilosc,
                        Rabat = 0,
                        DataRealizacji = DateTime.Now,
                        CzyAktywna = true
                    };
                    await _context.PozycjeZleceniaZakupu.AddAsync(orderItem);
                }
                await _context.SaveChangesAsync();
                
                cartB.ClearCart();

                return RedirectToAction("Summary", new { id = order.IdZleceniaZakupu });
            }
            return View();
        }
        public async Task<ActionResult> Summary(int id)
        {
            var order = await _context.ZleceniaZakupu
                .Include(z => z.RodzajTransportu)
                .Include(z => z.SposobDostawy)
                .Include(z => z.SposobPlatnosci)
                .Include(z => z.TypTransakcji)
                .Include(z => z.PozycjaZZ).ThenInclude(p=>p.Produkt).ThenInclude(c=>c.Cena)
                .Include(z => z.Kontrahent).ThenInclude(k => k.Adres)
                .FirstOrDefaultAsync(z => z.IdZleceniaZakupu == id);

            if (order == null)
            {
                return View("Error");
            }
            
            return View(order);
        }
    }
}

FirmaWebApp/Controllers/ProduktController.cs
using Firma.Data.Model;
using FirmaWebApp.Models.BusinessLogic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FirmaWebApp.Controllers
{
    public class ProduktController : ControllerWithLoggerAndContext
    {
        public ProduktController(ILogger<HomeController> logger, FirmaDbContext context) 
            : base(logger, context)
        {
        }
        public async Task<IActionResult> ProduktDetails(int id)
        {
            var typyproduktow = _context.TypyProduktow.ToList();
            ViewData["TypyProduktow"] = typyproduktow;
            var produkt = await _context.Produkty
                .Include(produkt=>produkt.Cena)
                .FirstOrDefaultAsync(p => p.IdProduktu == id && p.Cena
                                            .Where(c=>c.IdTypuCeny==1)
                                            .Any());
            return View(produkt);
        }
        public ActionResult AddToCart(int id)
        {
            CartB cart = new CartB(this._context, this.HttpContext);
            var item = _context.Produkty.Find(id);
            cart.AddToCart(item);
            return RedirectToAction("ProduktDetails", new { id = item.IdProduktu });
        }
    }
}

FirmaWebApp/Views/Cart/Index.cshtml
@model FirmaWebApp.Models.Shop.CartData
@{
    ViewData["Title"] = "Cart";
    Layout = "~/Views/Shared/_CartLayout.cshtml";
}
<div class="kontener">
    <h2>Mój koszyk</h2>
    <div>
        <table class="tab2">
            <colgroup>
                <col style="width:800px" />
                <col style="width:200px" />
                <col style="width:100px" />
                <col style="width:50px" />
            </colgroup>
            <tr>
                <th>
                    Nazwa produktu
                </th>
                <th>
                    Cena
                </th>
                <th>
                    Ilość
                </th>
                <th></th>
            </tr>
            @foreach (var item in Model.CartItems)
            {
                <tr>
                    <td>
                        <a asp-action="ProduktDetails" asp-controller="Produkt" asp-route-id="@item.IdProduktu">@item.Produkt?.Nazwa</a>
                    </td>
                    <td>
                        @item.Produkt?.Cena?.Where(c=>c.IdTypuCeny==1).Select(c=>c.Wartosc.ToString("N2") + " " + c.Waluta).FirstOrDefault()
                    </td>
                    <td>
                        @String.Format("{0:F}", item.Ilosc)
                    </td>
                    <td>
                        <a asp-action="RemoveFromCart" asp-controller="Cart" asp-route-id="@item.Id">Usuń</a>
                    </td>
                </tr>
            }
        </table>
    </div>
    <div>
        <h4>Razem: @Model.Total.ToString("N2") @Model.CartItems.Select(x=>x.Produkt?.Cena?.Select(w=>w.Waluta).First()).FirstOrDefault()</h4>
    </div>
    <div>
        <a class="btn btn-light" asp-action="KontrahentData" asp-controller="OrderData" style="margin:40px 0px 0px 0px">Zamów</a>
        <a class="btn btn-light" asp-action="Index" asp-controller="TypyProduktow" style="margin:40px 0px 0px 0px">Kupuj dalej</a>
    </div>
</div>